services:
#  youtube-statistics:
#    build:
#      context: .
#    ports:
#      - 3000:3000
#    volumes:
#      - /logs:/logs
  postgres:
    image: postgres:13
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker